spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            client-name: ${COGNITO_CLIENT_NAME}
            scope:
              - openid
              - email
              - aws.cognito.signin.user.admin
            redirect-uri: http://localhost:3000
        provider:
          cognito:
            issuer-uri: ${COGNITO_ISSUER_URI}
            user-name-attribute: cognito:username


  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

logging:
  level:
    root: INFO

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_SERVICE_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

