spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

app:
  datasource:
    #Galera - Soccer ???? ?? ??
    soccer:
      ddl-auto: update
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 1235

      rw:
        jdbc-url: jdbc:mysql://172.20.1.2:3306/soccer?allowPublicKeyRetrieval=true
      ro:
        jdbc-url: jdbc:mysql://172.20.1.3:3306/soccer?allowPublicKeyRetrieval=true








