server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
      url: ${DATABASE_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL_ROOT_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}

app:
  image-base-path: ${LOCAL_IMAGE_STORAGE}