spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

logging:
  level:
    root: INFO

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_SERVICE_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

