version: '2.23.0'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    environment:
      - DATABASE_ROOT_USERNAME
      - DATABASE_ROOT_PASSWORD
    networks:
      app-network:
        ipv4_address: 172.20.1.3

  tuktuk:
    build:
      context: .
      dockerfile: tuktuk.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    container_name: tuktuk-server
    depends_on:
      - mysql
    environment:
      - DATABASE_URL
      - DATABASE_ROOT_USERNAME
      - DATABASE_ROOT_PASSWORD
    networks:
      app-network:
        ipv4_address: 172.20.1.2

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
